# Generated by Django 4.2 on 2024-01-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RGBFrameSequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('rgb_strip', models.JSONField(blank=True, null=True, verbose_name='RGB strip sequence (json)')),
            ],
            options={
                'verbose_name_plural': 'RGB Frame sequences',
            },
        ),
    ]
