# Generated by Django 4.2 on 2024-01-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgbframesequences',
            name='current_sequences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
