# Generated by Django 4.2 on 2024-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_current_sequences_rgbframesequences_current_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgbframesequences',
            name='speed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rgbframesequences',
            name='times',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
