# Generated by Django 4.2 on 2024-01-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_rgbframesequences_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rgbframesequences',
            options={'verbose_name_plural': 'RGB frame sequence patterns'},
        ),
        migrations.AlterField(
            model_name='rgbframesequences',
            name='rgb_strip',
            field=models.JSONField(blank=True, null=True, verbose_name='Sequence patterns combination (json)'),
        ),
    ]
