# Generated by Django 4.2 on 2024-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_rgbframesequences_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgbframesequences',
            name='rgb_strip',
            field=models.JSONField(blank=True, null=True, verbose_name='RGB strip sequence pattern (json)'),
        ),
    ]
