# Generated by Django 4.2 on 2023-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularstoragepanel',
            name='grid_col',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modularstoragepanel',
            name='grid_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modularstoragepanelbase',
            name='grid_col',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modularstoragepanelbase',
            name='grid_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
