# Generated by Django 4.2 on 2023-06-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_content_type_connection_connection_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='connection_start',
            new_name='content_type',
        ),
    ]
