# Generated by Django 4.2 on 2023-06-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0007_rename_object_id_connection_start_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='end_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='end_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='start_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='start_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_type', to='contenttypes.contenttype'),
        ),
    ]
