# Generated by Django 4.2 on 2023-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_modularstoragepanel_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modularstoragepanel',
            name='module',
        ),
        migrations.AddField(
            model_name='modularstoragepanelbase',
            name='module',
            field=models.PositiveIntegerField(default=0, verbose_name='Module selected'),
        ),
    ]
