# Generated by Django 4.2 on 2023-08-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('projects', '0011_remove_modularstoragepanel_module_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModularStoragePanel',
            new_name='ModularStoragePanel3x3',
        ),
    ]
