# Generated by Django 4.2 on 2023-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_modularstoragepanel_modularstoragepanel3x3'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGBFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('rgb_strip', models.JSONField(blank=True, null=True, verbose_name='(Output) RGB strip')),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('grid_row', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_col', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='modularstoragepanel3x3',
            options={'verbose_name_plural': 'Modular storage panels 3x3'},
        ),
        migrations.AlterField(
            model_name='modularstoragepanel3x3',
            name='display_7_segment',
            field=models.FloatField(blank=True, null=True, verbose_name='(Output) 7 segments 4 digits display'),
        ),
        migrations.AlterField(
            model_name='modularstoragepanel3x3',
            name='leds_matrix',
            field=models.JSONField(blank=True, null=True, verbose_name='(Output) 3x3 RGB matrix'),
        ),
        migrations.AlterField(
            model_name='modularstoragepanelbase',
            name='rotary_switch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(Input) Rotating switch'),
        ),
    ]
