# Generated by Django 4.2 on 2024-01-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rgbframe_alter_modularstoragepanel3x3_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rgbframe',
            old_name='current_sequence',
            new_name='current_sequences',
        ),
    ]
