# Generated by Django 4.0 on 2023-03-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelArmazenamentoModular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, unique=True)),
                ('display', models.FloatField(null=True)),
                ('modulo', models.IntegerField(null=True)),
                ('campo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo1', to='componente.componente')),
                ('campo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo2', to='componente.componente')),
                ('campo3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo3', to='componente.componente')),
                ('campo4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo4', to='componente.componente')),
                ('campo5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo5', to='componente.componente')),
                ('campo6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo6', to='componente.componente')),
                ('campo7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo7', to='componente.componente')),
                ('campo8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo8', to='componente.componente')),
                ('campo9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo9', to='componente.componente')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='componente.categoria')),
            ],
            options={
                'verbose_name_plural': 'Painéis de armazenamento modular',
            },
        ),
    ]
