# Generated by Django 4.0 on 2023-03-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0001_initial'),
        ('projetos', '0006_painelarmazenamentomodular_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='componente.categoria', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot3', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot4', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot5', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot6', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot7', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot8', to='componente.componente', unique=True),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot9', to='componente.componente', unique=True),
        ),
    ]
