# Generated by Django 4.0 on 2023-03-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_alter_painelarmazenamentomodular_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='categoria',
        ),
    ]
