# Generated by Django 4.0 on 2023-03-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_painelarmazenamentomodular_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelDeArmazenamentoModularBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, unique=True)),
                ('display_oled', models.TextField(null=True, verbose_name="(Output) Display OLED 0.96'")),
                ('chave_rotativa', models.CharField(max_length=100, null=True, verbose_name='(Input) Chave rotativa')),
            ],
            options={
                'verbose_name_plural': 'Painéis de armazenamento modular base',
            },
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='modulo',
            new_name='modulo_selecionado',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot1',
            new_name='slot_1',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot2',
            new_name='slot_2',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot3',
            new_name='slot_3',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot4',
            new_name='slot_4',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot5',
            new_name='slot_5',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot6',
            new_name='slot_6',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot7',
            new_name='slot_7',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot8',
            new_name='slot_8',
        ),
        migrations.RenameField(
            model_name='painelarmazenamentomodular',
            old_name='slot9',
            new_name='slot_9',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='display',
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='display_de_7_segmentos',
            field=models.FloatField(null=True, verbose_name='(Output) Display de 7 segmentos e 4 dígitos'),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='matriz_de_leds',
            field=models.JSONField(null=True, verbose_name='(Output) Matriz 3x3 de Leds RGB'),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='nome',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='base',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='projetos.paineldearmazenamentomodularbase'),
        ),
    ]
