# Generated by Django 4.0 on 2023-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_paineldearmazenamentomodularbase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='display_de_7_segmentos',
            field=models.FloatField(blank=True, null=True, verbose_name='(Output) Display de 7 segmentos e 4 dígitos'),
        ),
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='matriz_de_leds',
            field=models.JSONField(blank=True, null=True, verbose_name='(Output) Matriz 3x3 de Leds RGB'),
        ),
        migrations.AlterField(
            model_name='paineldearmazenamentomodularbase',
            name='chave_rotativa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='(Input) Chave rotativa'),
        ),
        migrations.AlterField(
            model_name='paineldearmazenamentomodularbase',
            name='display_oled',
            field=models.TextField(blank=True, null=True, verbose_name="(Output) Display OLED 0.96'"),
        ),
    ]
