# Generated by Django 4.0 on 2023-03-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_alter_painelarmazenamentomodular_display_de_7_segmentos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paineldearmazenamentomodularbase',
            options={'verbose_name_plural': 'Bases dos painéis de armazenamento modular'},
        ),
    ]
