# Generated by Django 4.0 on 2023-03-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_alter_paineldearmazenamentomodularbase_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='modulo_selecionado',
        ),
    ]
