# Generated by Django 4.0 on 2023-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_remove_painelarmazenamentomodular_modulo_selecionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_1_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_2_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_3_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_4_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_5_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_6_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_7_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_8_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='painelarmazenamentomodular',
            name='slot_9_idx',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
