# Generated by Django 4.0 on 2023-03-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0001_initial'),
        ('projetos', '0013_painelarmazenamentomodular_slot_1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelarmazenamentomodular',
            name='slot_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='componente.componente'),
        ),
    ]
