# Generated by Django 4.0 on 2023-03-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_alter_painelarmazenamentomodular_slot_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_1_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_2_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_3_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_4_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_5_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_6_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_7_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_8_idx',
        ),
        migrations.RemoveField(
            model_name='painelarmazenamentomodular',
            name='slot_9_idx',
        ),
    ]
