# Generated by Django 4.0 on 2023-03-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='componente.categoria')),
            ],
            options={
                'verbose_name_plural': 'Tipos de componentes',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('limite', models.IntegerField(default=99, null=True)),
                ('tipo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='componente.tipodecomponente')),
            ],
        ),
    ]
