# Generated by Django 4.0 on 2022-08-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainelArmazenamentoModular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.FloatField(null=True)),
                ('modulo', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Painéis de armazenamento modular',
            },
        ),
    ]
