# Generated by Django 4.2 on 2023-06-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='components.category')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('limite', models.IntegerField(default=99, null=True)),
                ('tipo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='components.componenttype')),
            ],
        ),
    ]
